export const INITIAL_GALLERY_ITEMS = [
  {
    id: 'anillo-rolex',
    name: 'Anillos de Hombre & Sellos 18k',
    category: 'Anillos',
    price: '',
    description: 'Colección de anillos de hombre y sellos tallados en Oro 18k ley 750.',
    tag: '🌟 Destacado',
    spanClass: 'gallery-card--tall',
    media: [
      { type: 'video', url: '/media/anillo1-2.mp4' },
      { type: 'video', url: '/media/anillo1-9.mp4' },
      { type: 'image', url: '/media/anillo1-1.jpeg' },
      { type: 'image', url: '/media/anillo1-3.jpeg' },
      { type: 'image', url: '/media/anillo1-4.jpeg' },
      { type: 'image', url: '/media/anillo1-5.jpeg' },
      { type: 'image', url: '/media/anillo1-6.jpeg' },
      { type: 'image', url: '/media/anillo1-7.jpeg' },
      { type: 'image', url: '/media/anillo1-8.jpeg' },
    ],
  },
  {
    id: 'manilla-hilo-rojo',
    name: 'Pulseras en Hilo Rojo & Balines 18k',
    category: 'Pulseras',
    price: '',
    description: 'Pulseras tejidas en hilo rojo de alta durabilidad con balines y neoprenos en Oro 18k.',
    tag: '✨ Nuevo',
    spanClass: 'gallery-card--normal',
    media: [
      { type: 'video', url: '/media/manilla1-13.mp4' },
      { type: 'image', url: '/media/manilla1-10.jpeg' },
      { type: 'image', url: '/media/manilla1-11.jpeg' },
      { type: 'image', url: '/media/manilla1-12.jpeg' },
    ],
  },
  {
    id: 'manilla-hilo-negro',
    name: 'Pulseras Tejidas en Hilo Negro 18k',
    category: 'Pulseras',
    price: '',
    description: 'Diseños sobrios y elegantes tejidos en hilo negro con accesorios de Oro 18k.',
    tag: '🔥 Pieza Única',
    spanClass: 'gallery-card--normal',
    media: [
      { type: 'video', url: '/media/manilla2-18.mp4' },
      { type: 'image', url: '/media/manilla2-14.jpeg' },
      { type: 'image', url: '/media/manilla2-15.jpeg' },
      { type: 'image', url: '/media/manilla2-16.jpeg' },
      { type: 'image', url: '/media/manilla2-17.jpeg' },
    ],
  },
  {
    id: 'manilla-especial',
    name: 'Pulseras & Cadenas de Autor 18k',
    category: 'Pulseras',
    price: '',
    description: 'Piezas artesanales de autor elaboradas a mano en Oro 18k ley 750.',
    tag: '💎 Edición Limitada',
    spanClass: 'gallery-card--wide',
    media: [
      { type: 'video', url: '/media/manilla3-23.mp4' },
      { type: 'image', url: '/media/manilla3-19.jpeg' },
      { type: 'image', url: '/media/manilla3-20.jpeg' },
      { type: 'image', url: '/media/manilla3-21.jpeg' },
      { type: 'image', url: '/media/manilla3-22.jpeg' },
    ],
  },
  {
    id: 'coleccion-noctis',
    name: 'Colección Exclusiva Noctis 18k',
    category: 'Alta Joyería',
    price: '',
    description: 'Alta joyería Noctis. Joyas exclusivas en Oro de 18 Kilates con acabados de alta gama.',
    tag: '🌟 Destacado',
    spanClass: 'gallery-card--wide',
    media: [
      { type: 'image', url: '/media/nocti-24.jpeg' },
      { type: 'image', url: '/media/nocti-25.jpeg' },
      { type: 'image', url: '/media/nocti-26.jpeg' },
      { type: 'image', url: '/media/nocti-27.jpeg' },
      { type: 'image', url: '/media/nocti-28.jpeg' },
      { type: 'image', url: '/media/nocti-29.jpeg' },
      { type: 'image', url: '/media/nocti-30.jpeg' },
      { type: 'image', url: '/media/nocti-31.jpeg' },
    ],
  },
];
